"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-30 13:39:15.575333

Every persistent table from the PD6 domain model (DR-01..DR-08, FR-03, FR-05,
FR-43). `kb_chunks` deliberately has no `embedding` column and no vector
index: those are added manually in M4, once the embedding model is chosen
(ADR-04, ADR-07).

Autogenerated from the models, then hand-corrected in two ways:

1. The native PostgreSQL enum types are declared once and created before any
   table, then dropped after the tables on downgrade. Autogenerate renders a
   separate `sa.Enum` per column, which would emit a duplicate CREATE TYPE for
   the types several tables share (`species`, `vtl_category`, `user_role`,
   `job_status`) — including inside the ARRAY columns.
2. `case_no_seq` is added. P02 §2.1 specifies `cases.case_no` as coming from a
   sequence formatted as `C-0001`; the model carries only the unique string, so
   the sequence has to be created here. P04 reads it with
   `nextval('case_no_seq')`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- Native enum types (CLAUDE.md §6) -------------------------------------
# create_type=False: these are created and dropped explicitly below, never
# implicitly by op.create_table().

user_role = postgresql.ENUM(
    "INTAKE_STAFF",
    "VETERINARY_REVIEWER",
    "ADMINISTRATOR",
    name="user_role",
    create_type=False,
)
species = postgresql.ENUM("DOG", "CAT", name="species", create_type=False)
intake_channel = postgresql.ENUM(
    "WALK_IN", "PHONE", "MESSAGE", name="intake_channel", create_type=False
)
case_status = postgresql.ENUM(
    "SUBMITTED",
    "PROCESSING",
    "AWAITING_REVIEW",
    "MANUAL_TRIAGE_REQUIRED",
    "CONFIRMED",
    "ADJUSTED",
    "MANUALLY_TRIAGED",
    "CLOSED",
    name="case_status",
    create_type=False,
)
vtl_category = postgresql.ENUM(
    "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", name="vtl_category", create_type=False
)
kb_entry_status = postgresql.ENUM(
    "DRAFT", "PENDING_REVIEW", "ACTIVE", "RETIRED", name="kb_entry_status", create_type=False
)
confidence_level = postgresql.ENUM(
    "HIGH", "MEDIUM", "LOW", name="confidence_level", create_type=False
)
decision_type = postgresql.ENUM(
    "CONFIRM", "ADJUST", "MANUAL", name="decision_type", create_type=False
)
decision_direction = postgresql.ENUM(
    "UP", "DOWN", "SAME", "NONE", name="decision_direction", create_type=False
)
age_unit = postgresql.ENUM("MONTHS", "YEARS", name="age_unit", create_type=False)
sex = postgresql.ENUM("MALE", "FEMALE", "UNKNOWN", name="sex", create_type=False)
job_type = postgresql.ENUM(
    "PIPELINE_RUN", "REGENERATE", "EVAL_RUN", "KB_INDEX", name="job_type", create_type=False
)
job_status = postgresql.ENUM(
    "QUEUED", "RUNNING", "DONE", "FAILED", name="job_status", create_type=False
)

ENUM_TYPES = (
    user_role,
    species,
    intake_channel,
    case_status,
    vtl_category,
    kb_entry_status,
    confidence_level,
    decision_type,
    decision_direction,
    age_unit,
    sex,
    job_type,
    job_status,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ENUM_TYPES:
        enum_type.create(bind, checkfirst=True)

    # Source of cases.case_no, rendered as C-0001 by the case service (P04).
    op.execute("CREATE SEQUENCE case_no_seq AS bigint START WITH 1 INCREMENT BY 1")

    op.create_table(
        "presenting_complaints",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", user_role, nullable=False),
        sa.Column("can_approve_kb", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "NOT can_approve_kb OR role = 'VETERINARY_REVIEWER'",
            name="ck_users_can_approve_kb_requires_reviewer",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("role", user_role, nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_log_entity_type_entity_id_ts",
        "audit_log",
        ["entity_type", "entity_id", "ts"],
        unique=False,
    )
    op.create_table(
        "cases",
        sa.Column("case_no", sa.String(length=10), nullable=False),
        sa.Column("species", species, nullable=False),
        sa.Column("intake_channel", intake_channel, nullable=False),
        sa.Column("status", case_status, nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_no"),
    )
    op.create_index("ix_cases_status_created_at", "cases", ["status", "created_at"], unique=False)
    op.create_table(
        "evaluation_sets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["imported_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_entries",
        sa.Column("complaint_code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("species", postgresql.ARRAY(species), nullable=False),
        sa.Column("source_title", sa.String(length=300), nullable=True),
        sa.Column("source_publisher", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("access_date", sa.Date(), nullable=True),
        sa.Column("status", kb_entry_status, nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comments", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["complaint_code"], ["presenting_complaints.code"]),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_versions",
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_no"),
    )
    op.create_table(
        "clinical_notes",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("set_id", sa.UUID(), nullable=False),
        sa.Column("kb_version_id", sa.UUID(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", job_status, nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["kb_version_id"], ["kb_versions.id"]),
        sa.ForeignKeyConstraint(["set_id"], ["evaluation_sets.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_chunks",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["kb_entries.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_version_entries",
        sa.Column("kb_version_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["kb_entries.id"]),
        sa.ForeignKeyConstraint(["kb_version_id"], ["kb_versions.id"]),
        sa.PrimaryKeyConstraint("kb_version_id", "entry_id"),
    )
    op.create_table(
        "owner_descriptions",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "owner_references",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("contact_number", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "red_flag_rules",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("min_category", vtl_category, nullable=False),
        sa.Column("species", postgresql.ARRAY(species), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=True),
        sa.Column("is_placeholder", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["entry_id"], ["kb_entries.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "signalments",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("pet_name", sa.String(length=200), nullable=True),
        sa.Column("age_value", sa.Numeric(), nullable=True),
        sa.Column("age_unit", age_unit, nullable=True),
        sa.Column("sex", sex, nullable=False),
        sa.Column("neutered", sa.Boolean(), nullable=True),
        sa.Column("breed", sa.String(length=200), nullable=True),
        sa.Column("weight_kg", sa.Numeric(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "staff_decisions",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("type", decision_type, nullable=False),
        sa.Column("final_category", vtl_category, nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("reason_text", sa.Text(), nullable=True),
        sa.Column("direction", decision_direction, nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amends_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "type <> 'ADJUST' OR reason_code IS NOT NULL",
            name="ck_staff_decisions_reason_code_required_for_adjust",
        ),
        sa.ForeignKeyConstraint(["amends_id"], ["staff_decisions.id"]),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vignettes",
        sa.Column("set_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("species", species, nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_category", vtl_category, nullable=False),
        sa.Column("relevant_entry_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["set_id"], ["evaluation_sets.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_results",
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("vignette_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_corrected", sa.Boolean(), nullable=False),
        sa.Column("corrected_by", sa.UUID(), nullable=True),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(case_id IS NULL) <> (vignette_id IS NULL)",
            name="ck_extraction_results_case_xor_vignette",
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["corrected_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["vignette_id"], ["vignettes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("type", job_type, nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("vignette_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", job_status, nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["vignette_id"], ["vignettes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_status_run_after", "jobs", ["status", "run_after"], unique=False)
    op.create_table(
        "red_flag_alerts",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("rule_code", sa.String(length=100), nullable=False),
        sa.Column("matched_text", sa.Text(), nullable=False),
        sa.Column("min_category", vtl_category, nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["rule_code"], ["red_flag_rules.code"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_complaints",
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("complaint_code", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["complaint_code"], ["presenting_complaints.code"]),
        sa.ForeignKeyConstraint(["extraction_id"], ["extraction_results.id"]),
        sa.PrimaryKeyConstraint("extraction_id", "complaint_code"),
    )
    op.create_table(
        "recommendations",
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("vignette_id", sa.UUID(), nullable=True),
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("kb_version_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("category", vtl_category, nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", confidence_level, nullable=False),
        sa.Column("safety_floor_applied", sa.Boolean(), nullable=False),
        sa.Column(
            "safety_floor_rule_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "low_confidence_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(case_id IS NULL) <> (vignette_id IS NULL)",
            name="ck_recommendations_case_xor_vignette",
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["extraction_id"], ["extraction_results.id"]),
        sa.ForeignKeyConstraint(["kb_version_id"], ["kb_versions.id"]),
        sa.ForeignKeyConstraint(["vignette_id"], ["vignettes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendations_case_id_version",
        "recommendations",
        ["case_id", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_table(
        "evaluation_results",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("vignette_id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=True),
        sa.Column("extraction_id", sa.UUID(), nullable=True),
        sa.Column("predicted_category", vtl_category, nullable=True),
        sa.Column("stage_latencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["extraction_id"], ["extraction_results.id"]),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"]),
        sa.ForeignKeyConstraint(["run_id"], ["evaluation_runs.id"]),
        sa.ForeignKeyConstraint(["vignette_id"], ["vignettes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retrieved_references",
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("is_cited", sa.Boolean(), nullable=False),
        sa.Column("entry_title", sa.String(length=300), nullable=False),
        sa.Column("source_title", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("passage_text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["kb_chunks.id"]),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("retrieved_references")
    op.drop_table("evaluation_results")
    op.drop_index("ix_recommendations_case_id_version", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_table("extraction_complaints")
    op.drop_table("red_flag_alerts")
    op.drop_index("ix_jobs_status_run_after", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("extraction_results")
    op.drop_table("vignettes")
    op.drop_table("staff_decisions")
    op.drop_table("signalments")
    op.drop_table("red_flag_rules")
    op.drop_table("owner_references")
    op.drop_table("owner_descriptions")
    op.drop_table("kb_version_entries")
    op.drop_table("kb_chunks")
    op.drop_table("evaluation_runs")
    op.drop_table("clinical_notes")
    op.drop_table("kb_versions")
    op.drop_table("kb_entries")
    op.drop_table("evaluation_sets")
    op.drop_index("ix_cases_status_created_at", table_name="cases")
    op.drop_table("cases")
    op.drop_index("ix_audit_log_entity_type_entity_id_ts", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("presenting_complaints")

    op.execute("DROP SEQUENCE IF EXISTS case_no_seq")

    # Enum types go last: nothing may still depend on them.
    bind = op.get_bind()
    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(bind, checkfirst=True)
